
project_id = "vbrnyndzprufhtrwujdh"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.razorpay-webhook]
verify_jwt = false
